config/routes.rb
Launched::Application.routes.draw do
  get "help", :controller => "pages", :as => :help
  resources :plists do
    member do
      get :install
    end
  end
  root :to => "plists#new"
end

app/models/launchd_plist.rb
class LaunchdPlist < ActiveRecord::Base

  CRON_EXP = /^[\-\/*0-9,]+$/

  validates_presence_of :uuid, :command, :name
  validates_format_of :minute,
    :with => CRON_EXP, :allow_nil => true, :allow_blank => true
  validates_format_of :hour,
    :with => CRON_EXP, :allow_nil => true, :allow_blank => true
  validates_format_of :day_of_month,
    :with => CRON_EXP, :allow_nil => true, :allow_blank => true

  before_validation :generate_uuid, :on => :create

  def label
    name.downcase.gsub /\s+/, "_"
  end

  def weekday_list
    (weekdays || "").split(",").map(&:to_i)
  end

  def month_list
    (months || "").split(",").map(&:to_i)
  end

  protected

  def generate_uuid
    self.uuid = UUID.generate
  end

end

app/models/launchd_serializer.rb
class LaunchdSerializer
  attr_reader :plist

  def initialize(plist)
    @plist = plist
  end

  def to_plist
    attribute_hash.to_plist
  end

  protected

  def attribute_hash
    {}.tap do |attrs|
      attrs["Label"] = Launched::Application::DOMAIN + "." + plist.label
      attrs["ProgramArguments"] = [ "sh", "-c", plist.command]

      if intervals = calendar_intervals
        attrs["StartCalendarInterval"] = calendar_intervals
      end

      attrs["StartInterval"] = plist.interval if plist.interval
      attrs["RunAtLoad"] = true if plist.run_at_load
      attrs["LaunchOnlyOnce"] = true if plist.launch_only_once
      attrs["UserName"] = plist.user if plist.user.present?
      attrs["GroupName"] = plist.group if plist.group.present?
      attrs["RootDirectory"] = plist.root_directory if plist.root_directory.present?
      attrs["WorkingDirectory"] = plist.working_directory if plist.working_directory.present?
    end
  end

  def calendar_intervals
    crontab_expression = CrontabExpression.new(
      :minute => plist.minute,
      :hour => plist.hour,
      :day => plist.day_of_month,
      :day_of_week => plist.weekdays,
      :month => plist.months
    )

    intervals = crontab_expression.intervals.map do |i|
      capitalized = i.map do |k,v|
        if k.to_s == "day_of_week"
          ["Weekday", v]
        else
          [k.capitalize, v]
        end
      end
      Hash[capitalized]
    end

    if intervals.empty?
      nil
    elsif intervals.size == 1
      intervals.first
    else
      intervals
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end
end

app/controllers/plists_controller.rb
class PlistsController < ApplicationController

  before_filter :find_plist_by_uuid, :only => [:show, :edit, :install]

  def new
    @plist = LaunchdPlist.new
  end

  def create
    @plist = LaunchdPlist.new params[:plist]

    if @plist.save
      redirect_to plist_path(@plist.uuid)
    else
      render :action => :new
    end
  end

  def show
    @plist_xml = LaunchdSerializer.new(@plist).to_plist

    respond_to do |format|
      format.xml do
        filename = Launched::Application::DOMAIN + "." + @plist.label + ".xml"
        headers["Content-Disposition"] =
          %Q(attachment; filename="#{filename}"; size=#{@plist_xml.length})
        render :xml => @plist_xml
      end
      format.html
    end
  end

  def edit
    render :action => "new"
  end

  def install
    render :template => "plists/install.txt"
  end

  protected

  def find_plist_by_uuid
    @plist = LaunchdPlist.find_by_uuid(params[:id]) or raise ActiveRecord::RecordNotFound
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Launched</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "launched", root_path, :class => "brand" %>
          <span class="navbar-text">A launchd.plist generator</span>
          <ul class="nav pull-right">
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
      <footer class="footer">
        <p class="pull-right">
          Built by <a href="http://zerowidth.com/about.html">Nathan Witmer</a>,
          hosted on <a href="http://www.heroku.com/">heroku</a>,
          <a href="https://github.com/zerowidth/launched">source on github</a>.
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/pages/help.html.erb
<h2>Help!</h2>

<h3>What is this, anyway?</h3>

<p>
  Launchd was designed at Apple as a replacement for init.d, crond, rc.d, etc.
  Launchd not only provides everything that cron does, it can do so with even
  more flexibility and power. The only downside is that the <a
    href="https://developer.apple.com/library/mac/#documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html">XML
    configuration files required by launchd</a> are nowhere near as simple to
  write.
</p>

<p>
  That's where this application comes in. It's designed to be a simple way to
  generate common cron-style launchd plist files for use on your own system.
</p>

<h3>Installing a plist</h3>

<p>To install a plist to run as your user:</p>

<pre><code># Create a folder for for the plists, if it doesn't already exist
mkdir -p ~/Library/LaunchAgents

# Put your plist in this directory
cp ~/Downloads/<%= Launched::Application::DOMAIN %>.your_script.plist ~/Library/LaunchAgents

# And load it up with launchctl:
launchctl load -w ~/Library/LaunchAgents/<%= Launched::Application::DOMAIN %>.your_script.plist
</code></pre>

<p>
  If your plist needs to run as a different user, including root, you'll need to
  install it to the systemwide launch daemons folder instead:
</p>

<pre><code># Put your plist in the system directory
sudo cp ~/Downloads/<%= Launched::Application::DOMAIN %>.your_script.plist ~/Library/LaunchDaemons

# And load it up with launchctl:
sudo launchctl load -w /Library/LaunchDaemons/<%= Launched::Application::DOMAIN %>.your_script.plist
</code></pre>

<p>
  When you generate a launchd plist with this application, there are also
  instructions and scripts for installation on the generated plist's page.
</p>

<h3>Uninstalling a plist</h3>

<p>Uninstalling a plist is just as easy as installing it. For a user plist:</p>
<pre><code>launchctl load -w ~/Library/LaunchAgents/<%= Launched::Application::DOMAIN %>.your_script.plist</code></pre>

<p>And for root,</p>
<pre><code>sudo launchctl load -w /Library/LaunchDaemons/<%= Launched::Application::DOMAIN %>.your_script.plist</code></pre>

<h3>Debugging</h3>

<p>
  If your plist doesn't seem to be running correctly, you can debug it by
  looking at the logs in console.app. Fortunately, launchd prefixes any activity
  with the label defined in your plist. So, continuing with the above example,
  search for <code><%= Launched::Application::DOMAIN %>.your_script</code> to
  find any log entries related to your job.
</p>

<h3>Isn't there a tool to make this easier?</h3>

<p>
  Yes. <code>gem install lunchy &amp;&amp; lunchy --help</code>
</p>

<h3>Privacy and Security</h3>

<p>
  This application has no way of listing the plists that have been created so
  far, and each plist is identified by a UUID rather than an incrementing id, to
  make enumeration difficult. Still, you should ensure that you keep private
  data out of the plists if possible.
</p>

<p>
  To prevent accidental or malicious changes, it's not possible to edit a plist.
  Instead, each new version of a plist has a different identifier.
</p>

<h3>Learn More</h3>

<pre><code>man launchd
man launchd.plist
</code></pre>

<h3>Who's responsible for this nonsense?</h3>

<p>
  Feel free to blame <a href="http://zerowidth.com/about.html">Nathan Witmer</a>. Want to
  contribute? Find this on
  <a href="https://github.com/zerowidth/launched">github</a>.
</p>

app/views/plists/create.html.erb
<%= debug params %>

app/views/plists/install.txt.erb
<% filename = Launched::Application::DOMAIN + "." + @plist.label + ".plist" -%>
echo downloading <%= filename %>...
mkdir -p ~/Library/LaunchAgents
curl -o ~/Library/LaunchAgents/<%= filename %> <%= plist_url @plist.uuid, :format => :xml %>
echo installing <%= filename %>...
launchctl load -w ~/Library/LaunchAgents/<%= filename %>

app/views/plists/new.html.erb
<script type="text/javascript" charset="utf-8">
  $(function(){ plist.form_init(); });
</script>
<div class="row">
  <div class="span12">
    <%= form_for @plist, :as => :plist, :url => plists_path, :method => "post", :html => {:id => "plist", :class => "form-vertical"} do |f| %>

      <fieldset>
        <div class="row">
          <div class="span12">
            <legend>Basics</legend>
          </div>
        </div>

        <div class="row">

          <div class="span5">
            <div class="control-group">
              <%= f.label :name %>
              <%= f.text_field :name, :class => "span4" %>
            </div>
          </div>

          <div class="span7">
            <div class="control-group">
              <%= f.label :command %>
              <div class="input-prepend">
                <span class="add-on">sh -c</span>
                <%= f.text_field :command, :class => "span6" %>
              </div>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <div class="row">
          <div class="span12">
            <legend>Schedule</legend>
          </div>
        </div>

        <div class="row">
          <div class="span5">

            <div class="control-group">
              <%= f.label :minute %>
              <%= f.text_field :minute, :class => "span1" %>
              <span class="help-inline">Cron syntax: <code>*</code>, or e.g. <code>0</code>, <code>0,30</code>, <code>*/5</code></span>
            </div>

            <div class="control-group">
              <%= f.label :hour %>
              <%= f.text_field :hour, :class => "span1" %>
              <span class="help-inline">Cron syntax, <code>0-23</code></span>
            </div>

            <div class="control-group">
              <%= f.label :day_of_month, "Day of Month" %>
              <%= f.text_field :day_of_month, :class => "span1" %>
              <span class="help-inline">Cron syntax: <code>1-31</code>, <code>1,15</code>, etc.</span>
            </div>
          </div>

          <div class="span7">

            <div class="control-group">
              <label>Weekday</label>
              <div class="btn-group" data-toggle="buttons-checkbox">
                <% Date::ABBR_DAYNAMES.each.with_index do |day, i| -%>
                  <a href="#" class="btn <%= "active" if @plist.weekday_list.include? i %>"><%= day %></a>
                <% end -%>
              </div>
              <%= f.hidden_field :weekdays %>
              <span class="help-inline">None selected implies "all".</span>
            </div>

            <div class="control-group">
              <label>Month</label>
              <div class="controls">
                <div class="btn-group" data-toggle="buttons-checkbox">
                  <% Date::ABBR_MONTHNAMES.each.with_index do |month, i| -%>
                    <% next unless month # 0 is nil -%>
                    <a href="#" class="btn <%= "active" if @plist.month_list.include? i %>"><%= month %></a>
                  <% end -%>
                </div>
                <%= f.hidden_field :months %>
                <span class="help-inline">None selected implies "all".</span>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :interval, "Run Interval" %>
              <div class="controls">
                <%= f.text_field :interval, :class => "span1" %>
                <span class="help-inline">Run at this interval (seconds)</span>
              </div>
            </div>

          </div>
        </div>
      </fieldset>


      <fieldset>

        <div class="row">
          <div class="span12">
            <legend>Extras</legend>
          </div>
        </div>

        <div class="row">
          <div class="span5">

            <div class="control-group">
              <%= f.label :run_at_load %>
              <div class="controls">
                <label class="checkbox">
                  <%= f.check_box :run_at_load %>
                  Runs once when loaded (including at boot)
                </label>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :launch_only_once %>
              <label class="checkbox">
                <%= f.check_box :launch_only_once %>
                Run this plist only once ever, unless the system is rebooted
              </label>
            </div>

          </div>

          <div class="span7">

            <div class="row">
              <div class="control-group span3">
                <%= f.label :user %>
                <%= f.text_field :user %>
                <p>Run as this user</p>
              </div>

              <div class="control-group span4">
                <%= f.label :group %>
                <%= f.text_field :group %>
                <p>and/or this group</p>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :root_directory, "Root Directory" %>
              <%= f.text_field :root_directory, :class => "span6" %>
              <p>Run with this root directory (via chroot)</p>
            </div>

            <div class="control-group">
              <%= f.label :working_directory, "Working Directory" %>
              <%= f.text_field :working_directory, :class => "span6" %>
              <p>Run with this working directory</p>
            </div>

        </div>
      </fieldset>


    <div class="form-actions">
      <div class="pull-right">
        <button type="submit" class="btn btn-success">
          <i class="icon-ok icon-white"></i>
          Create .plist
        </button>
      </div>
      <% unless @plist.new_record? -%>
        <p>
          <span class="label label-warning">Notice</span>
          For security, editing a .plist creates a new, different entry.
        </p>
      <% end -%>
    </div>

    <% end -%>
  </div>
</div>

app/views/plists/show.html.erb
<script type="text/javascript" charset="utf-8">
  $(function(){ plist.show_init(); });
</script>
<h2><%= @plist.label %>.plist</h2>

<h3>Install</h3>
<p>
  <code id="install">curl <%= install_plist_url(@plist.uuid) %> | sh</code>
  <a href="#" title="copy to clipboard" class="install"><i class="icon-share"></i></a> |
  <%= link_to "source", install_plist_path(@plist.uuid) %>
</p>

<h3>Your .plist</h3>
<p class="pull-right">
  <a href="#" title="copy to clipboard" class="plist_xml"><i class="icon-share"></i></a> |
  <%= link_to "edit", edit_plist_path(@plist.uuid) %> |
  <%= link_to "download", plist_path(@plist.uuid, :format => :xml) %>
</p>

<p><tt><%= @plist.label %>.plist</tt> running <code><%= @plist.command %></code>:</p>
<pre id="plist_xml"><code><%= @plist_xml %></code></pre>

<h3>Manual Install</h3>

<% filename = Launched::Application::DOMAIN + "." + @plist.label + ".plist" -%>

<p>Manual install:</p>
<pre><code>mkdir -p ~/Library/LaunchAgents
curl -o ~/Library/LaunchAgents/<%= filename %> <%= plist_url @plist.uuid, :format => :xml %>
launchctl load -w ~/Library/LaunchAgents/<%= filename %>
</code></pre>

<p>Or, to install as root:</p>
<pre><code>curl -o ~/Downloads/<%= filename %> <%= plist_url @plist.uuid, :format => :xml %>
sudo cp ~/Downloads/<%= filename %> /Library/LaunchDaemons
sudo launchctl load -w /Library/LaunchDaemons/<%= filename %>
</code></pre>